export type Option = {
  value: string
  label: string
  description?: string
  // HSL hue used for the gradient fallback when imagePath is missing or fails
  // to load. Kept so the UI never renders an empty card.
  hue?: number
  // Path under /public — points to the per-option preview JPG generated by
  // scripts/generate-builder-option-images.ts. CardsGrid / SwatchesGrid
  // overlay this image on top of the gradient.
  imagePath?: string
}

export const STYLE_OPTIONS: Option[] = [
  { value: 'realistic', label: 'Realistic', description: 'Photo-quality, lifelike companion', hue: 290, imagePath: '/builder/art-style/realistic.jpg' },
  { value: 'anime', label: 'Anime', description: 'Stylized illustration, expressive', hue: 330, imagePath: '/builder/art-style/anime.jpg' },
]

export const AGE_RANGE_OPTIONS: Option[] = [
  { value: 'young_adult', label: '21-25', description: 'Young adult', hue: 200, imagePath: '/builder/age/young_adult.jpg' },
  { value: 'adult', label: '25-35', description: 'In her prime', hue: 280, imagePath: '/builder/age/adult.jpg' },
  { value: 'mature', label: '35-45', description: 'Mature, experienced', hue: 320, imagePath: '/builder/age/mature.jpg' },
  { value: 'experienced', label: '45-55', description: 'Confidently mature', hue: 0, imagePath: '/builder/age/experienced.jpg' },
]

// Onboarding's "average" is labelled "Athletic" — point the image at the
// athletic asset so the card visual matches the label the user reads.
export const BODY_OPTIONS: Option[] = [
  { value: 'slender', label: 'Slim', description: 'Petite, lithe build', hue: 200, imagePath: '/builder/body-type/slender.jpg' },
  { value: 'average', label: 'Athletic', description: 'Toned, balanced', hue: 160, imagePath: '/builder/body-type/athletic.jpg' },
  { value: 'curvy', label: 'Curvy', description: 'Full-figured, soft curves', hue: 340, imagePath: '/builder/body-type/curvy.jpg' },
  { value: 'voluptuous', label: 'Voluptuous', description: 'Bold, hourglass', hue: 0, imagePath: '/builder/body-type/voluptuous.jpg' },
]

export const BUST_OPTIONS: Option[] = [
  { value: 'small', label: 'Small', description: 'Petite & natural', hue: 190, imagePath: '/builder/breast-size/small.jpg' },
  { value: 'medium', label: 'Medium', description: 'Balanced', hue: 280, imagePath: '/builder/breast-size/medium.jpg' },
  { value: 'large', label: 'Large', description: 'Full', hue: 330, imagePath: '/builder/breast-size/large.jpg' },
  { value: 'huge', label: 'Huge', description: 'Bombshell', hue: 0, imagePath: '/builder/breast-size/huge.jpg' },
]

export const BUTT_OPTIONS: Option[] = [
  { value: 'small', label: 'Toned', description: 'Athletic & firm', hue: 160, imagePath: '/builder/butt-size/small.jpg' },
  { value: 'medium', label: 'Round', description: 'Balanced & shapely', hue: 280, imagePath: '/builder/butt-size/medium.jpg' },
  { value: 'large', label: 'Big', description: 'Full & curvy', hue: 330, imagePath: '/builder/butt-size/large.jpg' },
  { value: 'huge', label: 'Bubble', description: 'Pronounced bubble shape', hue: 0, imagePath: '/builder/butt-size/huge.jpg' },
]

export const HAIR_COLOR_OPTIONS: Option[] = [
  { value: 'blonde', label: 'Blonde', hue: 50, imagePath: '/builder/hair-color/blonde.jpg' },
  { value: 'brunette', label: 'Brunette', hue: 25, imagePath: '/builder/hair-color/brunette.jpg' },
  { value: 'black', label: 'Black', hue: 270, imagePath: '/builder/hair-color/black.jpg' },
  { value: 'redhead', label: 'Red', hue: 10, imagePath: '/builder/hair-color/redhead.jpg' },
  { value: 'auburn', label: 'Auburn', hue: 20, imagePath: '/builder/hair-color/auburn.jpg' },
  { value: 'platinum', label: 'Platinum', hue: 60, imagePath: '/builder/hair-color/platinum.jpg' },
]

// Onboarding hair styles are length+style combos. Map each to the closest
// generated asset so the cards render an actual photo of that shape; the
// downstream HAIR_STYLE_MAP in OnboardingWizard already decomposes these.
export const HAIR_STYLE_OPTIONS: Option[] = [
  { value: 'long_straight', label: 'Long & straight', description: 'Sleek, flowing', hue: 220, imagePath: '/builder/hair-length/long.jpg' },
  { value: 'long_wavy', label: 'Long & wavy', description: 'Soft beachy waves', hue: 280, imagePath: '/builder/hair-style/wavy.jpg' },
  { value: 'long_curly', label: 'Long & curly', description: 'Voluminous curls', hue: 340, imagePath: '/builder/hair-style/curly.jpg' },
  { value: 'medium_wavy', label: 'Medium wavy', description: 'Shoulder-length waves', hue: 30, imagePath: '/builder/hair-length/medium.jpg' },
  { value: 'short_bob', label: 'Short bob', description: 'Chic, modern bob', hue: 190, imagePath: '/builder/hair-length/short.jpg' },
  { value: 'pixie', label: 'Pixie', description: 'Bold, short crop', hue: 0, imagePath: '/builder/hair-length/short.jpg' },
  { value: 'ponytail', label: 'Ponytail', description: 'Sporty, gathered up', hue: 130, imagePath: '/builder/hair-style/ponytail.jpg' },
  { value: 'updo', label: 'Updo', description: 'Elegant, swept up', hue: 260, imagePath: '/builder/hair-style/bun.jpg' },
]

export const EYE_COLOR_OPTIONS: Option[] = [
  { value: 'blue', label: 'Blue', hue: 210, imagePath: '/builder/eye-color/blue.jpg' },
  { value: 'brown', label: 'Brown', hue: 25, imagePath: '/builder/eye-color/brown.jpg' },
  { value: 'green', label: 'Green', hue: 130, imagePath: '/builder/eye-color/green.jpg' },
  { value: 'hazel', label: 'Hazel', hue: 35, imagePath: '/builder/eye-color/hazel.jpg' },
  { value: 'gray', label: 'Gray', hue: 220, imagePath: '/builder/eye-color/gray.jpg' },
  { value: 'amber', label: 'Amber', hue: 40, imagePath: '/builder/eye-color/amber.jpg' },
]

export const PERSONALITY_OPTIONS: Option[] = [
  {
    value: 'sweet_girlfriend',
    label: 'Sweet',
    description: 'Warm, caring, deeply affectionate',
    hue: 340,
    imagePath: '/builder/archetype/sweet_girlfriend.jpg',
  },
  {
    value: 'shy_romantic',
    label: 'Shy',
    description: 'Gentle, soft-spoken, romantic',
    hue: 320,
    imagePath: '/builder/archetype/shy_romantic.jpg',
  },
  {
    value: 'adventurous_spirit',
    label: 'Adventurous',
    description: 'Bold, spontaneous, fun',
    hue: 30,
    imagePath: '/builder/archetype/adventurous_spirit.jpg',
  },
  {
    value: 'mysterious_one',
    label: 'Mysterious',
    description: 'Enigmatic, intriguing, deep',
    hue: 270,
    imagePath: '/builder/archetype/mysterious_one.jpg',
  },
  {
    value: 'confident_leader',
    label: 'Confident',
    description: 'Assured, decisive, commanding',
    hue: 0,
    imagePath: '/builder/archetype/confident_leader.jpg',
  },
  {
    value: 'intellectual',
    label: 'Intellectual',
    description: 'Witty, thoughtful, curious',
    hue: 200,
    imagePath: '/builder/archetype/intellectual.jpg',
  },
]

export const NAME_SUGGESTIONS = [
  'Aria',
  'Luna',
  'Mia',
  'Zoe',
  'Eva',
  'Hana',
  'Sofia',
  'Jade',
  'Isabella',
  'Diana',
]

export type OnboardingChoices = {
  style?: string
  ageRange?: string
  body?: string
  bust?: string
  butt?: string
  hairColor?: string
  hairStyle?: string
  eyeColor?: string
  personality?: string
  name?: string
}

export const TOTAL_STEPS = 10
