export { FeaturedCompanions } from './FeaturedCompanions'
export { HowItWorks } from './HowItWorks'
export { PricingTeaser } from './PricingTeaser'
export { TrustStrip } from './TrustStrip'
export { FaqSection } from './FaqSection'
export { FinalCta } from './FinalCta'
export { PersonaCard } from './PersonaCard'
export { getExploreCharacters, getFeaturedCharacters, type FeaturedCharacter } from './featured-data'
